<?php
/* @var $this Mage_Reports_Block_Product_Viewed */
?>
<?php
if(Mage::getSingleton('customer/session')->isLoggedIn()){
    $customer = Mage::getSingleton('customer/session')->getCustomer();

    if(!$customer->getPreference()){
        $block = $this->getLayout()->createBlock('reports/product_viewed');
        $_productCollection = $block->getItemsCollection();
    }else{
        $preference = Mage::getModel('customerpreference/customerpreference')->getCollection()
                                      ->addFieldToSelect('preference_id')
                                      ->addFieldToFilter('entity_id', array('eq' => $customer->getId()))
                                      ->getFirstItem();

        $preferedAttributes = Mage::getModel('customerpreference/attribute')->getCollection()
                                      ->addFieldToFilter('preference_id', array('eq' => $preference->getId()));

        $visibility = array(
          Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH,
          Mage_Catalog_Model_Product_Visibility::VISIBILITY_IN_CATALOG,
          Mage_Catalog_Model_Product_Visibility::VISIBILITY_IN_SEARCH
        );
        $productCollection = Mage::getModel('catalog/product')->getCollection()
                                          ->addAttributeToSelect('*')
                                          ->addAttributeToFilter('visibility' , $visibility)
                                          ->addAttributeToFilter('status', '1');
        foreach ($preferedAttributes as $attr) {
            $productCollection->addAttributeToFilter($attr->getAttributeCode(), array('in' => explode(",",$attr->getValues())));
        }
        if($productCollection->count() > 0){
            $_productCollection = $productCollection;
        }else{
            $block = $this->getLayout()->createBlock('reports/product_viewed');
            $_productCollection = $block->getItemsCollection();
        }
    }
}else{

    $category = Mage::getModel('catalog/category')->load($this->getCategoryId());
    $_productCollection = Mage::getModel('catalog/product')
        ->getCollection()
        ->addAttributeToSelect('*')
        ->addCategoryFilter($category)
        ->setOrder('price', 'ASC')
        ->load();
}
?>
<?php if ($_productCollection): ?>
    <?php foreach ($_productCollection as $_product): ?>
    <?php  if(!$_product->isSaleable() && !Mage::getStoreConfig('cataloginventory/options/show_out_of_stock'))continue; ?>
    <?php
        $widthBig=258;
        $heightBig=245;
        $widthSmall=71;
        $heightSmall=65;
    $price=$this->getPriceHtml($_product, true);
    $izotope=true;
    ?>
        <?php
        /*
         * Product Preview HTML  is using in many blocks (category listing, shortcodes).
         * That is why Product Preview HTML generation collected in one function drawProductPreview()
         * You can edit this function  in file \app\code\local\Etheme\Megatronconfig\Helper\Data.php
        */
        ?>
        <?php
        $colorswatches='';
        if (Mage::getStoreConfig('configswatches/general/enabled', Mage::app()->getStore())) {
            $colorswatches=$this->getLayout()->createBlock('core/template')->setTemplate('configurableswatches/catalog/product/list/swatches.phtml')->setProduct($_product)->toHtml();
        }
        ?>
        <!--PRODUCT-->
        <?php  echo Mage::helper('buyshopconfig')->getProductHtml($_product,$this,$widthBig,$heightBig,3,true,true,false,true,$price,$izotope, $this->getCategoryId(),$colorswatches)?>
        <?php echo Mage::helper('buyshopconfig')->getProductHover($_product,$this,$widthBig,$heightBig,$widthSmall,$heightSmall,$type='',true,true,$price, $colorswatches)?>
        <!--PRODUCT EOF-->

    <?php endforeach ?>
    <?php
    if (Mage::getStoreConfig('configswatches/general/enabled', Mage::app()->getStore())) {
        echo $this->getLayout()->createBlock('configurableswatches/catalog_media_js_list')->setTemplate('configurableswatches/catalog/media/js.phtml')->setProductCollection($_productCollection)->toHtml();
    }
    ?>
<?php endif; ?>
