<h1><?php echo $this->__('Help us know you better') ?></h1>
<div id="messages_customer_preference"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<p><?php echo $this->__('In less than 5 mins...') ?></p>
<form action="<?php echo $this->getUrl('customer/account/preferencePost') ?>" enctype="multipart/form-data" id="preference_form" method="post">
    <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
    <div class="fieldset">
        <label for="fullname"><span>A</span><?php echo $this->__('Full Name')?></label>
        <input type="text" name="fullname" class="input-text required-entry" id="fullname" />
    </div>
    <div class="fieldset">
        <label><span>B</span><?php echo $this->__('Number of family members who live with you')?></label>
        <div class="members_list_block">
          <ul class="members_list">
              <li><input type="text" title="Name" placeholder="Name" name="members[0][name]" class="input-text" /></li>
              <li><input type="text" title="Relationship" placeholder="Relationship" name="members[0][relationship]" class="input-text" /></li>
              <li><input type="text" title="Age" placeholder="Age" name="members[0][age]" class="input-text" /></li>
          </ul>
        </div>
        <div class="members_control">
            <button type="button" id="add_member"><span><?php echo $this->__('Add Member')?></span></button>
        </div>
    </div>
    <div class="fieldset">
        <label><span>C</span><?php echo $this->__("What's your style?")?></label>
        <?php
          $attribute_code = 'style';
          $attribute = Mage::getSingleton('eav/config')
    ->getAttribute(Mage_Catalog_Model_Product::ENTITY, $attribute_code);
          if ($attribute->usesSource()):
            $attributeOptions = $attribute->getSource()->getAllOptions(false);
            foreach ($attributeOptions as $_option):
        ?>
        	<div class="cell">
            <input type="checkbox" name="attribute[style][]" id="style<?php echo $_option['value']?>" value="<?php echo $_option['value']?>" />
            <label for="style<?php echo $_option['value']?>"><?php echo $_option['label']?></label>
            
            </div>
            <?php endforeach; ?>
        <?php endif;?>
    </div>
    <div class="fieldset">
        <label><span>D</span><?php echo $this->__("Colors that make you happy")?></label>
        <?php
          $attribute_code = 'color';
          $attribute = Mage::getSingleton('eav/config')
    ->getAttribute(Mage_Catalog_Model_Product::ENTITY, $attribute_code);
          if ($attribute->usesSource()):
            $attributeOptions = $attribute->getSource()->getAllOptions(false);
            foreach ($attributeOptions as $_option):
        ?>
        	<div class="color-box">
            <input type="checkbox" name="attribute[color][]" id="color<?php echo $_option['value']?>" value="<?php echo $_option['value']?>" />
            <label for="color<?php echo $_option['value']?>"><?php echo $_option['label']?></label>
            
            </div>
            <?php endforeach; ?>
        <?php endif;?>
    </div>
    <div class="fieldset">
        <label><span>E</span><?php echo $this->__("Looking for")?></label>
        <?php
          $attribute_code = 'looking_for';
          $attribute = Mage::getSingleton('eav/config')
    ->getAttribute(Mage_Catalog_Model_Product::ENTITY, $attribute_code);
          if ($attribute->usesSource()):
            $attributeOptions = $attribute->getSource()->getAllOptions(false);
            foreach ($attributeOptions as $_option):
        ?>
        	<div class="item-box">
            
            <input type="checkbox" name="attribute[looking_for][]" id="looking_for<?php echo $_option['value']?>" value="<?php echo $_option['value']?>" />
            <label for="looking_for<?php echo $_option['value']?>"><?php echo $_option['label']?></label>
            </div>
            <?php endforeach; ?>
        <?php endif;?>
    </div>
    <div class="fieldset">
        <label><span>F</span><?php echo $this->__('Your Budget range')?></label>
        <div class="input-box">
        <input type="text" name="budget_from" class="input-text" title="Budget From" placeholder="Budget From" />
        </div>
        <div class="input-box">
        <input type="text" name="budget_to" class="input-text" title="Budget To" placeholder="Budget To" />
        </div>
    </div>

    <div class="button-set">
        <a href="<?php echo $this->getUrl('customer/account')?>"><span><< <?php echo $this->__('Back')?></span></a>
        <button type="submit" class="btn"><span><span><?php echo $this->__('Complete')?></span></span></button>
    </div>
</form>
<script type="text/javascript">
 var preferenceForm = new VarienForm('preference_form');

 var memberListsFieldsHtml = jQuery("#preference_form").find('div.members_list_block').html();
 jQuery("#add_member").click(function(){
    var listCount = jQuery("#preference_form").find("ul.members_list").size();
    var newMemberHtml = memberListsFieldsHtml.replace(/[0]/g, listCount);
    jQuery("#preference_form").find('div.members_list_block').append(newMemberHtml);
 })

</script>
