<?php if(Mage::getSingleton('customer/session')->isLoggedIn() && Mage::getSingleton('core/session')->getShownPopup() == 0): ?>
  <?php
  $customer = Mage::getSingleton('customer/session')->getCustomer();
  if($customer->getPreference() != 1):
    Mage::getSingleton('core/session')->setShownPopup(1);
    ?>
    <div class="back-layout">&nbsp;</div>
    <div class="login-popup">
        <div class="close"><a href="javascript:void();" class="cls-btn">X</a></div>
        <div class="left-block"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)?>wysiwyg/category-banner.jpg" alt="" /></div>
        <div class="right-block">
            <h1>Hello <?php echo $customer->getName()?>,</h1>
            <p>Welcome to FOMA</p>
            <p>Looking to buy a new Sofa? The timing couldn't have been better, we have just restocked a whole lot of sofa designers for Diwali.</p>
            <p>Not Sure where to start? Click on the below link "Know me better", create an account and leave the rest to us.</p>
            <p>We are a JSW venture and we believe in <span>"Bringing positive transformation to every life we touch"</span></p>
            <a href="<?php echo $this->getUrl('customer/account/preference')?>"><span>Know me better</span></a>
        </div>
    </div>
    <script type="text/javascript">
    jQuery(document).ready(function(){
        jQuery("div.login-popup a.cls-btn").click(function(){
            jQuery("div.back-layout, div.login-popup").hide();
        });
    });
    </script>
  <?php endif; ?>
<?php endif; ?>
