<h4><i class="icon-facebook"></i><?php echo $this->__('FACEBOOK') ?></h4>
<div class="fb_outer">


    <div id="fb-root"></div>
    <script>(function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s);
            js.id = id;
            js.src = "//connect.facebook.net/<?php echo Mage::app()->getLocale()->getLocaleCode()?>/sdk.js#xfbml=1&version=v2.4";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>

    <div class="fb-page" data-href="https://www.facebook.com/<?php echo Mage::getStoreConfig('buyshopconfig/social_accounts/facebook_profile_name') ?>" data-small-header="true"
         data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true" data-show-posts="false">
        <div class="fb-xfbml-parse-ignore">
            <blockquote cite="https://www.facebook.com/<?php echo Mage::getStoreConfig('buyshopconfig/social_accounts/facebook_profile_name') ?>"><a href="https://www.facebook.com/<?php echo Mage::getStoreConfig('buyshopconfig/social_accounts/facebook_profile_name') ?>"><?php echo Mage::getStoreConfig('buyshopconfig/social_accounts/facebook_profile_name') ?></a></blockquote>
        </div>
    </div>
</div>


